datasources:
  default:
    url: jdbc:postgresql://localhost:5432/key_manager
    driverClassName: org.postgresql.Driver
    username: keyManager
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update