datasources:
  default:
    url: jdbc:postgresql://localhost:5432/key_manager
    driverClassName: org.postgresql.Driver
    username: keyManager
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update

grpc:
  server:
    port: ${SERVER_PORT:50051}

erpItau:
  contas:
    url: "http://localhost:9091/api/v1/clientes"

bcb:
  keys:
    url: "http://localhost:8082/api/v1/pix/keys"